# Generated by Django 2.2 on 2020-03-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('contacting_for', models.CharField(choices=[('Please Choose', 'Please Choose'), ('Training', 'Training'), ('Web Applications', 'Web Applications'), ('Android/IOS Apps', 'Android/IOS Apps')], default='Please Choose', max_length=30)),
                ('message', models.TextField()),
            ],
        ),
    ]
