# Generated by Django 2.2 on 2020-03-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200304_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquire_Course_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('select_course', models.CharField(choices=[('Python Web Development', 'Python Web Development'), ('Java Web Development', 'Java Web Development'), ('Full Stack Training', 'Full Stack Training'), ('Java & Python', 'Java & Python')], default='Python Web Development', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
