# Generated by Django 2.2 on 2020-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_enquire_course_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('choice_one', models.CharField(max_length=60)),
                ('choice_two', models.CharField(max_length=60)),
                ('choice_three', models.CharField(max_length=60)),
                ('choice_four', models.CharField(max_length=60)),
                ('answer', models.CharField(max_length=60)),
            ],
        ),
    ]
